PORTNAME=               pfSense-pkg-wallguard
DISTVERSIONPREFIX=      v
DISTVERSION=            0.1.0
PORTREVISION=           1
CATEGORIES=             security

MAINTAINER=             support@nullnet.ai
COMMENT=                WallGuard pfSense package
WWW=                    https://github.com/NullNet-ai/wallguard

LICENSE=                MIT

USES=                   cargo
USE_GITHUB=             yes
GH_ACCOUNT=             NullNet-ai
GH_PROJECT=             wallguard

SUB_FILES=              pkg-install pkg-deinstall
SUB_LIST=               PORTNAME=${PORTNAME}

.include <bsd.port.mk>
