CARGO_CRATES= bincode-1.3.3                  \
	      chrono-0.4.39                  \
	      clap-4.5.27              	     \
	      nullnet-libconfmon-0.1.1       \
	      nullnet-libtoken-0.1.0         \
	      nullnet-traffic-monitor-0.1.0  \
	      nullnet-wallguard-server-0.1.3 \
	      once_cell-1.20.2               \
	      sysinfo-0.33.1                 \
	      tokio-1.43.0                   \
	      uuid-1.12.1
